require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const playerRoutes = require('./routes/playerRoutes');
const userRoutes = require('./routes/userRoutes');
const authRoutes = require('./routes/authRoutes');
const visitRoutes = require('./routes/visitRoutes');
const attachmentRoutes = require('./routes/attachmentRoutes');
const certificateRoutes = require('./routes/certificateRoutes');
const auditLogRoutes = require('./routes/auditLogRoutes');
const playerStatusHistoryRoutes = require('./routes/playerStatusHistoryRoutes');
const visitPcmaRoutes = require('./routes/visitPcmaRoutes');
const visitImpedanceRoutes = require('./routes/visitImpedanceRoutes');
const visitGpsRoutes = require('./routes/visitGpsRoutes');
const visitInjuriesRoutes = require('./routes/visitInjuriesRoutes');
const visitNutritionRoutes = require('./routes/visitNutritionRoutes');
const visitCareRoutes = require('./routes/visitCareRoutes');
const visitExamenMedicalRoutes = require('./routes/visitExamenMedicalRoutes');
const visitSoinsRoutes = require('./routes/visitSoinsRoutes');
const injuryExamRoutes = require('./routes/injuryExamRoutes');
const injuryInterventionRoutes = require('./routes/injuryInterventionRoutes');
const notificationRoutes = require('./routes/notificationRoutes');
const reportRoutes = require('./routes/reportRoutes');
const planSemaineNutritionRoutes = require('./routes/planSemaineNutritionRoutes');
const mealTypeRoutes = require('./routes/mealTypeRoutes');
const mealItemRoutes = require('./routes/mealItemRoutes');
const sequelize = require('./config/db');
const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('../swagger.json');

const app = express();
app.use(express.json());
app.use(cors());
app.use(helmet());

app.use('/auth', authRoutes);
app.use('/users', userRoutes);
app.use('/players', playerRoutes);
app.use('/visits', visitRoutes);
app.use('/attachments', attachmentRoutes);
app.use('/certificates', certificateRoutes);
app.use('/audit_log', auditLogRoutes);
app.use('/player_status_history', playerStatusHistoryRoutes);
app.use('/visit_pcma', visitPcmaRoutes);
app.use('/visit_impedance', visitImpedanceRoutes);
app.use('/visit_gps', visitGpsRoutes);
app.use('/visit_injuries', visitInjuriesRoutes);
app.use('/visit_nutrition', visitNutritionRoutes);
app.use('/visit_care', visitCareRoutes);
app.use('/visit_examen_medical', visitExamenMedicalRoutes);
app.use('/visit_soins', visitSoinsRoutes);
app.use('/injury_exams', injuryExamRoutes);
app.use('/injury_interventions', injuryInterventionRoutes);
app.use('/notifications', notificationRoutes);
app.use('/reports', reportRoutes);
app.use('/plan_semaine_nutrition', planSemaineNutritionRoutes);
app.use('/meal_types', mealTypeRoutes);
app.use('/meal_items', mealItemRoutes);
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

sequelize.sync().then(() => console.log('DB OK'));

module.exports = app;
